### PR TITLE
=htc #864 fix race condition in ResponseRendererSpec

### LINKED ISSUE #864: FAILED: ResponseRendererSpec -> The response preparation logic should properly render The 'Connection' header should be rendered correctly
https://jenkins.akka.io:8498/job/pr-validator-akka-http/743/testReport/junit/akka.http.impl.engine.rendering/ResponseRendererSpec/The_response_preparation_logic_should_properly_render_The__Connection__header_should_be_rendered_correctly/

### PR DESCRIPTION
**Pull request by jrudolph**
The idea is to provide a stage / API that allows to find out the result
of running elements through a flow. The race condition previously was that
finding out whether the flow was completed could only be observed by waiting
for some amount of time.

This adds a new test utility stage that injects an event into the mailbox
of the ActorGraphInterpeter (via AsyncCallback) which is hoped to be only
processed after all internal events have been processed. This seems to work
reliably as long as the complete flow is fused and synchronous and the whole
processing needs less events than the event queue processes in one go.

Fixes #864

### CODE REVIEW

**Comment by jrudolph** [comment]
PLS BUILD

File: akka-http-core/src/test/scala/akka/http/impl/util/CollectionStage.scala [hunk 1]
```diff
@@ -0,0 +1,127 @@
...
+  sealed trait State
+  case object Uninitialized extends State
+  case class Scheduled(callback: Promise[(Seq[T], Boolean)]) extends State
+  case object Initialized extends State
+  case class Completed(elements: Try[(Seq[T], Boolean)]) extends State
+
+  def createLogicAndMaterializedValue(inheritedAttributes: Attributes): (GraphStageLogic, Collect[T]) = {
+    val logic = new GraphStageLogic(shape) with Collect[T] with InHandler {
+      var collectedElements = new VectorBuilder[T]()
+      @volatile var state = new AtomicReference[State](Uninitialized)
```
Comment (jonas) [inline akka-http-core/src/test/scala/akka/http/impl/util/CollectionStage.scala]: Does this need to be a `var` to trigger a special memory access? I didn't find any assignments to this reference.

**Comment by jrudolph** [comment]
Thanks, good point, that var is left over from a previous version.

Am 21.08.2017 4:52 nachm. schrieb "Jonas Fonseca" <notifications@github.com

**Comment by jrudolph** [comment]
PLS BUILD

**Comment by jrudolph** [comment]
PLS BUILD

**Comment by jrudolph** [comment]
Something is still broken but the failures don't reproduce on my machine.

**Comment by raboof** [comment]
`ResponseRendererSpec` fails with timeouts fairly reliably for me when I run `test` in `akka-http-core`, but not when I run `testOnly *ResponseRendererSpec`

**Comment by jrudolph** [comment]
Ah, thanks good suggestion. I'll try that.

**Comment by jrudolph** [comment]
The new infrastructure had indeed a small race condition. Should be fixed now :crossed_fingers:.

**Comment by jrudolph** [comment]
PLS BUILD

File: akka-http-core/src/test/scala/akka/http/impl/util/CollectionStage.scala [hunk 2]
```diff
@@ -0,0 +1,127 @@
...
+      }
+
+      def collectAndCompleteNow(): Future[(Seq[T], Boolean)] = {
+        val p = Promise[(Seq[T], Boolean)]()
+
+        @tailrec def handleState(): Unit =
+          state.get() match {
+            case Initialized ⇒
+              if (!state.compareAndSet(Initialized, Scheduled(p))) handleState()
+              else collectNowCallback.invoke(p)
```
Comment (jrudolph) [inline akka-http-core/src/test/scala/akka/http/impl/util/CollectionStage.scala]: Had to move the callback invocation here so that it cannot overtake the state change (or be even invoked multiple times).
