### PR TITLE
In WithPriorKnowledgeSpec and H2cUpgradeSpec, use new Http2FrameProbe for analyzing frames

### LINKED ISSUE #2734: Failed: akka.http.impl.engine.http2.WithPriorKnowledgeSpec.An HTTP server with PriorKnowledge should respond to cleartext HTTP/2 requests with cleartext HTTP/2
https://jenkins.akka.io:8498/job/akka-http-nightly/630/AKKA_VERSION=release-2.5,Node=akka-http-nightly-node,SCALA_VERSION=2.13.0,jdk=AdoptOpenJDK%208/testReport/junit/akka.http.impl.engine.http2/WithPriorKnowledgeSpec/An_HTTP_server_with_PriorKnowledge_should_respond_to_cleartext_HTTP_2_requests_with_cleartext_HTTP_2/

```
Stacktrace

sbt.ForkMain$ForkError: org.scalatest.exceptions.TestFailedException: HEADERS was not equal to SETTINGS
	at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:343)
	at org.scalatest.Matchers$ShouldMethodHelper$.shouldMatcher(Matchers.scala:6723)
	at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6759)
	at akka.http.impl.engine.http2.WithPriorKnowledgeSpec.$anonfun$new$4(WithPriorKnowledgeSpec.scala:60)
```

### PR DESCRIPTION
**Pull request by jrudolph**
Fixes #2734 and #2782.

Probably TCP frames were coalesced so multiple frames were received in one go
which wasn't expected. The new Http2FrameProbe can deal with that more
gracefully.

### CODE REVIEW

File: akka-http2-support/src/test/scala/akka/http/impl/engine/http2/WithPriorKnowledgeSpec.scala [hunk 1]
```diff
@@ -6,28 +6,21 @@ package akka.http.impl.engine.http2
...
+import akka.stream.OverflowStrategy
+import akka.stream.scaladsl.{ Keep, Source, Tcp }
 import akka.util.ByteString
 
 import scala.concurrent.Future
 
-class WithPriorKnowledgeSpec extends AkkaSpec("""
-    akka.loglevel = debug
-    akka.loggers = ["akka.http.impl.util.SilenceAllTestEventListener"]
+class WithPriorKnowledgeSpec extends AkkaSpecWithMaterializer("""
```
Comment (jrudolph) [inline akka-http2-support/src/test/scala/akka/http/impl/engine/http2/WithPriorKnowledgeSpec.scala]: @viktorklang summoned you for review in case you are interested because you contributed this test here.

File: akka-http2-support/src/test/scala/akka/http/impl/engine/http2/WithPriorKnowledgeSpec.scala [hunk 2]
```diff
@@ -45,47 +38,29 @@ class WithPriorKnowledgeSpec extends AkkaSpec("""
...
-          .toMat(Sink.queue())(Keep.both)
+          .toMat(fromServer.sink)(Keep.left)
           .run()
 
       // Obtained by converting the input request bytes from curl with --http2-prior-knowledge
       // This includes port 9009 as 'authority', which our server accepts.
       source.offer("UFJJICogSFRUUC8yLjANCg0KU00NCg0KAAASBAAAAAAAAAMAAABkAARAAAAAAAIAAAAAAAAECAAAAAAAP/8AAQAAHgEFAAAAAYKEhkGKCJ1cC4Fw3HwAf3qIJbZQw6u20uBTAyovKg==").futureValue
 
-      // read settings frame
-      val responseSettings = sink.pull().futureValue
```
Comment (jrudolph) [inline akka-http2-support/src/test/scala/akka/http/impl/engine/http2/WithPriorKnowledgeSpec.scala]: That pulled probably in more than one frame (coalesced by TCP) so the next assertions were failing.

File: akka-http2-support/src/test/scala/akka/http/impl/engine/http2/H2cUpgradeSpec.scala [hunk 3]
```diff
@@ -47,31 +40,24 @@ Upgrade: h2c
...
 
 """
-      val sink = Source.single(ByteString(upgradeRequest)).concat(Source.maybe)
-        .via(Tcp().outgoingConnection(binding.localAddress.getHostName, binding.localAddress.getPort))
-        .runWith(Sink.queue())
-      val response = sink.pull().futureValue.get.map(_.toChar).mkString
-      response should include("HTTP/1.1 101 Switching Protocols")
-      response should include("Upgrade: h2c")
-      response should include("Connection: upgrade")
-      val responseBody = sink.pull().futureValue.get
```
Comment (jrudolph) [inline akka-http2-support/src/test/scala/akka/http/impl/engine/http2/H2cUpgradeSpec.scala]: In the failing case, probably this one pulled in the HTTP/1.1 headers plus the SETTINGS frame (coalesced by TCP), so the assertion on the SETTINGS frame type below failed.

File: akka-http2-support/src/test/scala/akka/http/impl/engine/http2/H2cUpgradeSpec.scala [hunk 4]
```diff
@@ -47,31 +40,24 @@ Upgrade: h2c
...
-      val length = reader.readShortBE() << 8 | reader.readByte()
+      Source.single(ByteString(upgradeRequest)).concat(Source.maybe)
+        .via(Tcp().outgoingConnection(binding.localAddress.getHostName, binding.localAddress.getPort))
+        .runWith(frameProbe.sink)
 
-      val tpe = Http2Protocol.FrameType.byId(reader.readByte())
-      tpe should be(Http2Protocol.FrameType.SETTINGS)
+      @tailrec def readToEndOfHeader(currentlyRead: String = ""): String =
+        if (currentlyRead.endsWith("\r\n\r\n")) currentlyRead
+        else readToEndOfHeader(currentlyRead + frameProbe.plainDataProbe.expectBytes(1).utf8String)
```
Comment (jrudolph) [inline akka-http2-support/src/test/scala/akka/http/impl/engine/http2/H2cUpgradeSpec.scala]: Really efficient way to find the end of headers.

File: akka-http2-support/src/test/scala/akka/http/impl/engine/http2/WithPriorKnowledgeSpec.scala (hunk 1 above)
Comment (viktorklang) [reply akka-http2-support/src/test/scala/akka/http/impl/engine/http2/WithPriorKnowledgeSpec.scala]: Thanks, @jrudolph—I trust your judgement on this PR!
