### PR TITLE
fix(http2): h2c via Upgrade

### LINKED ISSUE #3998: h2c via Upgrade: "Cannot pull port twice" error
When using h2c (plaintext HTTP/2) via the 'Upgrade' mechanism, `Http2ServerDemux` seems to pull the import port twice on initialization:

```
[info] [ERROR] [01/11/2022 09:29:28.598] [ServerTest-akka.actor.default-dispatcher-6] [akka://ServerTest/system/StreamSupervisor-0/flow-3-1-mapAsyncUnordered] Error during preStart in [akka.http.impl.engine.http2.Http2ServerDemux@51f5b4c4]: Cannot pull port (Demux.substreamIn(537254184)) twice
[info] java.lang.IllegalArgumentException: Cannot pull port (Demux.substreamIn(537254184)) twice
[info] 	at akka.stream.stage.GraphStageLogic.pull(GraphStage.scala:518)
[info] 	at akka.http.impl.engine.http2.Http2Demux$$anon$1.preStart(Http2ServerDemux.scala:167)
[info] 	at akka.stream.impl.fusing.GraphInterpreter.init(GraphInterpreter.scala:292)
[info] 	at akka.stream.impl.fusing.GraphInterpreterShell.init(ActorGraphInterpreter.scala:575)
```

This seems to have been broken since 7f7350a7bd64c2b8365c46e58c69d104745b76cf

### PR DESCRIPTION
**Pull request by raboof**
When `SETTINGS_MAX_CONCURRENT_STREAMS` was set in the initial settings from
the `Upgrade` request, the input would be pulled twice, which is an error.

Fixes #3998

### CODE REVIEW

File: akka-http-core/src/main/scala/akka/http/impl/engine/http2/Http2Demux.scala [hunk 1]
```diff
@@ -255,10 +255,13 @@ private[http2] abstract class Http2Demux(http2Settings: Http2CommonSettings, ini
         if (initialRemoteSettings.nonEmpty) {
           debug(s"Applying ${initialRemoteSettings.length} initial settings!")
           applyRemoteSettings(initialRemoteSettings)
+          // applyRemoteSettings may or may not have pulled `substreamIn`
+          tryPullSubStreams()
```
Comment (jrudolph) [inline akka-http-core/src/main/scala/akka/http/impl/engine/http2/Http2Demux.scala:259]: Could we just `tryPullSubStreams` all the time for simplicity?

File: akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ServerDemuxSpec.scala [hunk 2]
```diff
@@ -0,0 +1,57 @@
...
+import akka.http.impl.engine.http2.FrameEvent.{ ParsedHeadersFrame, Setting, SettingsAckFrame, SettingsFrame, WindowUpdateFrame }
+import akka.http.impl.engine.http2.Http2Protocol.SettingIdentifier
+import akka.http.impl.util.AkkaSpecWithMaterializer
+import akka.http.scaladsl.settings.Http2ServerSettings
+import akka.stream.scaladsl.{ BidiFlow, Flow, Keep }
+import akka.stream.testkit.scaladsl.{ TestSink, TestSource }
+import akka.util.{ ByteString, OptionVal }
+
+/**
+ * low-level tests testing Http2ServerDemux in isolation
```
Comment (jrudolph) [inline akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ServerDemuxSpec.scala:12]: Can we put an end-to-end test into `H2cUpgradeSpec`, instead?

Comment (raboof) [reply akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ServerDemuxSpec.scala:16]: Perhaps both? It might be helpful to document how `Http2ServerDemuxSpec` was supposed to behave in this low-level test

File: akka-http2-support/src/test/scala/akka/http/impl/engine/http2/H2cUpgradeSpec.scala [hunk 3]
```diff
@@ -30,9 +30,17 @@ class H2cUpgradeSpec extends AkkaSpecWithMaterializer("""
...
     // https://tools.ietf.org/html/rfc7540#section-3.2
-    "respond with HTTP 101" in {
+    "respond with HTTP 101 and no initial settings" in {
       // Not the whole frame, but only the identifiers and values - so an empty string for 0 settings is valid:
-      val settings = ""
+      testWith("")
+    }
+
+    "respond with HTTP 101 and some initial settings" in {
+      // Not the whole frame, but only the identifiers and values - so an empty string for 0 settings is valid:
```
Comment (jrudolph) [inline akka-http2-support/src/test/scala/akka/http/impl/engine/http2/H2cUpgradeSpec.scala:39]: Is the comment still applicable? Maybe also add a comment of the decoding of what the string mean.

**Review by jrudolph — APPROVED** [review]
LGTM (maybe change the comment below)

File: akka-http2-support/src/test/scala/akka/http/impl/engine/http2/H2cUpgradeSpec.scala (hunk 3 above)
Comment (raboof) [reply akka-http2-support/src/test/scala/akka/http/impl/engine/http2/H2cUpgradeSpec.scala]: woops, made that more clear now

File: akka-http2-support/src/test/scala/akka/http/impl/engine/http2/H2cUpgradeSpec.scala [hunk 4]
```diff
@@ -30,9 +32,26 @@ class H2cUpgradeSpec extends AkkaSpecWithMaterializer("""
...
+    "respond with HTTP 101 and no initial settings" in {
+      val settings = encode(Nil)
+      // Settings are placed directly in the HTTP header, without any framing,
+      // so 'no settings' just yields the empty string:
+      settings shouldBe ""
+      testWith(settings)
+    }
+
+    "respond with HTTP 101 and some initial settings" in {
+      // real-world settings example as used by curl
```
Comment (jrudolph) [inline akka-http2-support/src/test/scala/akka/http/impl/engine/http2/H2cUpgradeSpec.scala:44]: Great thanks!
