### PR TITLE
=htp #1569 avoid relying on racy temporaryHostNameAndPort()

### LINKED ISSUE #1569: FAILED akka.http.scaladsl.server.HttpAppSpec.HttpApp should start only with host and port
https://jenkins.akka.io:8498/job/pr-validator-akka-http/1775/testReport/junit/akka.http.scaladsl.server/HttpAppSpec/HttpApp_should_start_only_with_host_and_port/

```
Error Message

Futures timed out after [5 seconds]

Stacktrace

java.util.concurrent.TimeoutException: Futures timed out after [5 seconds]
	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:223)
	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:227)
	at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:190)
	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
	at scala.concurrent.Await$.result(package.scala:190)
	at akka.http.scaladsl.server.HttpAppSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$10.apply(HttpAppSpec.scala:93)
	at akka.http.scaladsl.server.HttpAppSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$mcV$sp$10.apply(HttpAppSpec.scala:88)
	at akka.http.scaladsl.server.HttpAppSpec.withMinimal(HttpAppSpec.scala:71)
	at akka.http.scaladsl.server.HttpAppSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(HttpAppSpec.scala:88)
	at akka.http.scaladsl.server.HttpAppSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(HttpAppSpec.scala:88)
	at akka.http.scaladsl.server.HttpAppSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(HttpAppSpec.scala:88)
```

### PR DESCRIPTION
**Pull request by jrudolph**
Fixes #1569.

### CODE REVIEW

File: akka-http-tests/src/test/scala/akka/http/javadsl/server/HttpAppSpec.scala [hunk 1]
```diff
@@ -147,18 +145,18 @@ class HttpAppSpec extends AkkaSpec with RequestBuilding with Eventually {
 
     "notify" when {
 
-      "shutting down" in withSneaky { (sneaky, host, port) ⇒
+      "shutting down" in withSneaky { sneaky ⇒
 
         val server = Future {
-          sneaky.startServer(host, port, ServerSettings.create(ConfigFactory.load))
+          sneaky.startServer("localhost", 0, ServerSettings.create(ConfigFactory.load))
```
Comment (ktoso) [inline akka-http-tests/src/test/scala/akka/http/javadsl/server/HttpAppSpec.scala]: I remember perhaps @patriknw mentioning that binding to localhost (or was it 127.0.0.1) did not work for him sometimes...? Do we have a preference where we should bind to? We use either in this PR

Comment (jrudolph) [reply akka-http-tests/src/test/scala/akka/http/javadsl/server/HttpAppSpec.scala]: I used `127.0.0.1` where it is later checked and `localhost` otherwise. The previous version also used `localhost` through the default of `temporaryServerHostnameAndPort` so hopefully it will be fine.

Comment (ktoso) [reply akka-http-tests/src/test/scala/akka/http/javadsl/server/HttpAppSpec.scala]: Okey cool, thanks for checking!
