### PR TITLE
core: remove some instances of failing `temporaryServerHostnameAndPort` usages in test

### LINKED ISSUE #2953: Failed: akka.http.scaladsl.ClientServerSpec.The low-level HTTP infrastructure should properly bind a server with a default port set via settings
https://jenkins.akka.io:8498/job/akka-http-nightly/22/testReport/

```
java.net.BindException: Cannot assign requested address
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:67)
	at akka.testkit.SocketUtil$.$anonfun$temporaryServerAddresses$1(SocketUtil.scala:97)
	at scala.collection.generic.GenTraversableFactory.fill(GenTraversableFactory.scala:92)
	at akka.testkit.SocketUtil$.temporaryServerAddresses(SocketUtil.scala:81)
	at akka.testkit.SocketUtil$.temporaryServerAddress(SocketUtil.scala:74)
	at akka.testkit.SocketUtil$.temporaryServerHostnameAndPort(SocketUtil.scala:106)
	at akka.http.scaladsl.ClientServerSpec.$anonfun$new$3(ClientServerSpec.scala:76)
```

### PR DESCRIPTION
**Pull request by jrudolph**
Fixes #2953

### CODE REVIEW

File: akka-http-core/src/test/scala/akka/http/scaladsl/ClientServerSpec.scala [hunk 1]
```diff
@@ -64,22 +64,20 @@ class ClientServerSpec extends AnyWordSpec with Matchers with BeforeAndAfterAll
...
       sub.cancel()
     }
 
     "properly bind a server with a default port set via settings" in {
-      val (hostname, port) = SocketUtil.temporaryServerHostnameAndPort()
       val probe = TestSubscriber.manualProbe[Http.IncomingConnection]()
-      val settings = ServerSettings(system).withDefaultHttpPort(port)
-      val binding = Http().bind(hostname, settings = settings).to(Sink.fromSubscriber(probe)).run()
+      // not really testing anything here, problem is that it is hard to find an unused port otherwise
+      val settings = ServerSettings(system).withDefaultHttpPort(0)
```
Comment (jrudolph) [inline akka-http-core/src/test/scala/akka/http/scaladsl/ClientServerSpec.scala]: I guess that's somewhat awkward / useless but temporaryServerHostnameAndPort seems to fail in weird ways.

File: akka-http-core/src/test/scala/akka/http/scaladsl/ClientServerSpec.scala [hunk 2]
```diff
@@ -64,22 +64,20 @@ class ClientServerSpec extends AnyWordSpec with Matchers with BeforeAndAfterAll
   "The low-level HTTP infrastructure" should {
 
     "properly bind a server" in {
-      val (hostname, port) = SocketUtil.temporaryServerHostnameAndPort()
       val probe = TestSubscriber.manualProbe[Http.IncomingConnection]()
-      val binding = Http().bind(hostname, port).to(Sink.fromSubscriber(probe)).run()
+      val binding = Http().bind("0.0.0.0", 0).to(Sink.fromSubscriber(probe)).run()
```
Comment (raboof) [inline akka-http-core/src/test/scala/akka/http/scaladsl/ClientServerSpec.scala]: since `0.0.0.0` binds to all IP's, I guess `127.0.0.1` is a bit more conservative?
```suggestion
      val binding = Http().bind("127.0.0.1", 0).to(Sink.fromSubscriber(probe)).run()
```

File: akka-http-core/src/test/scala/akka/http/scaladsl/ClientServerSpec.scala [hunk 3]
```diff
@@ -64,22 +64,20 @@ class ClientServerSpec extends AnyWordSpec with Matchers with BeforeAndAfterAll
...
       val probe = TestSubscriber.manualProbe[Http.IncomingConnection]()
-      val settings = ServerSettings(system).withDefaultHttpPort(port)
-      val binding = Http().bind(hostname, settings = settings).to(Sink.fromSubscriber(probe)).run()
+      // not really testing anything here, problem is that it is hard to find an unused port otherwise
+      val settings = ServerSettings(system).withDefaultHttpPort(0)
+      val binding = Http().bind("0.0.0.0", settings = settings).to(Sink.fromSubscriber(probe)).run()
       val sub = probe.expectSubscription() // if we get it we are bound
-      val address = Await.result(binding, 1.second.dilated).localAddress
-      address.getPort shouldEqual port
+      Await.result(binding, 1.second.dilated).unbind()
```
Comment (raboof) [inline akka-http-core/src/test/scala/akka/http/scaladsl/ClientServerSpec.scala]: I guess we should check we did *not* bind to port 80 here then?

Comment (jrudolph) [reply akka-http-core/src/test/scala/akka/http/scaladsl/ClientServerSpec.scala]: Hmm, yes an ephemeral port range shouldn't be in that range. On the other hand, the test user shouldn't be able to bind ephemeral ports as well, so I'm not sure we win something in practice here.

Comment (jrudolph) [reply akka-http-core/src/test/scala/akka/http/scaladsl/ClientServerSpec.scala]: added
