### PR TITLE
Content-Disposition filename encoding fix #1240

### LINKED ISSUE #1240: Incorrect handling of `filename`, `filename*` in Content-Disposition header
This issue is visible in Play when we're sending a result. Play creates a header value like the following:

```
Content-Disposition: inline; filename="测 试.tmp"; filename*=utf-8''%E6%B5%8B%20%E8%AF%95.tmp
```

Akka HTTP parses this value in Play's `AkkaModelConversion` class, then renders the result as:

```
Content-Disposition: inline; filename="utf-8''%E6%B5%8B%20%E8%AF%95.tmp"
```

I believe this shows that Akka HTTP has bugs in both parsing and rendering the header.

* When parsing the header, the `filename*` parameter is preferred over the `filename`, since it comes second in the parameter list. This is correctly handled. However, the `filename*` has a special prefix (`utf8''`) that specifies the character encoding. This prefix should be used by the parser to set the character encoding, but not included in the filename itself. Akka HTTP appears to be including this value in the filename itself, rather than using it to specify a character set when decoding.

* When rendering the header, the `filename` parameter should probably only include "safe" ISO-8859-1, characters. Unsafe characters that need escaping should probably be stripped out, rather than encoded with `%`, like Akka HTTP does. This is because RFC2616 says that `\` should be used for quoting strings here. To be safe, complex characters could be excluded from the `filename` parameter and encoded properly in the `filename*` parameter instead. Modern clients will recognise and correctly handle the `filename*` parameter, ignoring the `filename` parameter. The `filename*` parameter can include the true filename, encoded and percent-escaped as per RFC6266. The suggested encoding is UTF-8, since it is mandatory for clients to support this encoding.

See:
* Related Play issue: https://github.com/playframework/playframework/issues/7501
* RFC about the filename parameter: https://tools.ietf.org/html/rfc6266#section-4.3
* Example Content-Disposition: https://tools.ietf.org/html/rfc6266#section-5
* RFC about mandatory client encodings: https://tools.ietf.org/html/rfc5987#section-3.2
* How to encode `*` parameters with non-standard characters: https://tools.ietf.org/html/rfc2231#section-4
* How to encode non-`*` parameters: https://tools.ietf.org/html/rfc2616#section-2.2

### PR DESCRIPTION
**Pull request by guntiso**

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @guntiso,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[https://www.lightbend.com/contribute/cla](https://www.lightbend.com/contribute/cla)

**Review by raboof — APPROVED** [review]
This looks great! 

Refs #1066 & #1240

File: akka-http-core/src/main/scala/akka/http/scaladsl/model/headers/headers.scala [hunk 1]
```diff
@@ -455,13 +456,29 @@ final case class `Content-Location`(uri: Uri) extends jm.headers.ContentLocation
...
  */
 object `Content-Disposition` extends ModeledCompanion[`Content-Disposition`]
 final case class `Content-Disposition`(dispositionType: ContentDispositionType, params: Map[String, String] = Map.empty)
   extends jm.headers.ContentDisposition with RequestResponseHeader {
   def renderValue[R <: Rendering](r: R): r.type = {
+    import Rendering.{ contentDispositionFilenameSafeChars => safeChars }
     r ~~ dispositionType
-    params foreach { case (k, v) => r ~~ "; " ~~ k ~~ '=' ~~#! v }
+    val renderExtFilename =
+      params.get("filename").map(safeChars.indexOfFirstMismatch(_) >= 0) getOrElse false
```
Comment (jrudolph) [inline akka-http-core/src/main/scala/akka/http/scaladsl/model/headers/headers.scala:468]: Can this be rewritten as something like `params.get("filename").exists(safeChars(_))`?

File: akka-http-core/src/main/scala/akka/http/scaladsl/model/headers/headers.scala [hunk 2]
```diff
@@ -455,13 +456,29 @@ final case class `Content-Location`(uri: Uri) extends jm.headers.ContentLocation
...
+    val withExtParams =
+      if (renderExtFilename && !params.contains("filename*"))
```
Comment (jrudolph) [inline akka-http-core/src/main/scala/akka/http/scaladsl/model/headers/headers.scala:470]: I think we should document that render logic somewhere. So, it is:

 * if `filename` exists and contains unsafe chars => also render `filename*`
 * if explicit `filename*` exists => don't generate `filename*` automatically

File: akka-http-core/src/main/scala/akka/http/scaladsl/model/headers/headers.scala [hunk 3]
```diff
@@ -455,13 +456,29 @@ final case class `Content-Location`(uri: Uri) extends jm.headers.ContentLocation
...
+        params + ("filename*" -> params("filename"))
+      else params
+    withExtParams foreach {
+      case (k, v) if k == "filename" =>
```
Comment (jrudolph) [inline akka-http-core/src/main/scala/akka/http/scaladsl/model/headers/headers.scala:474]: Ok, so here we always edit `filename` to contain only safe chars.

File: akka-http-core/src/main/scala/akka/http/scaladsl/model/headers/headers.scala [hunk 4]
```diff
@@ -455,13 +456,29 @@ final case class `Content-Location`(uri: Uri) extends jm.headers.ContentLocation
...
+        r ~~ "; " ~~ k ~~ '=' ~~ '"'
+        r.putReplaced(v, keep = safeChars, placeholder = '?') ~~ '"'
+      case (k, v) if k endsWith "*" =>
+        r ~~ "; " ~~ k ~~ '=' ~~ "UTF-8''"
```
Comment (jrudolph) [inline akka-http-core/src/main/scala/akka/http/scaladsl/model/headers/headers.scala:478]: So, we always render UTF-8, sounds reasonable.

Comment (jrudolph) [reply akka-http-core/src/main/scala/akka/http/scaladsl/model/headers/headers.scala:478]: Also, we never render a language tag, which is fine as we don't know any.

File: akka-http-core/src/main/scala/akka/http/scaladsl/model/headers/headers.scala [hunk 5]
```diff
@@ -455,13 +456,29 @@ final case class `Content-Location`(uri: Uri) extends jm.headers.ContentLocation
...
+      params.get("filename").map(safeChars.indexOfFirstMismatch(_) >= 0) getOrElse false
+    val withExtParams =
+      if (renderExtFilename && !params.contains("filename*"))
+        params + ("filename*" -> params("filename"))
+      else params
+    withExtParams foreach {
+      case (k, v) if k == "filename" =>
+        r ~~ "; " ~~ k ~~ '=' ~~ '"'
+        r.putReplaced(v, keep = safeChars, placeholder = '?') ~~ '"'
+      case (k, v) if k endsWith "*" =>
```
Comment (jrudolph) [inline akka-http-core/src/main/scala/akka/http/scaladsl/model/headers/headers.scala:477]: I guess this whole logic should be moved to a more general place for wider adoption, but for this PR we can leave it here.

**Review by jrudolph — COMMENTED** [review]
Looks very promising, thanks, @guntiso! I haven't fully reviewed yet but annotated a few assumptions / implementation choices that we need to document somewhere.

File: akka-http-core/src/main/scala/akka/http/scaladsl/model/headers/headers.scala (hunk 2 above)
Comment (jrudolph) [reply akka-http-core/src/main/scala/akka/http/scaladsl/model/headers/headers.scala:470]: > if `filename` exists and contains unsafe chars => also render `filename*`

IIRC there's some contention about whether to render both `filename*` and `filename`. Is there any data about what is best (basically, how browsers interpret those)? Does order matter?

Comment (raboof) [reply akka-http-core/src/main/scala/akka/http/scaladsl/model/headers/headers.scala:470]: https://tools.ietf.org/html/rfc6266#appendix-D suggests they should both be rendered and `filename` should come first - but I'm not sure how outdated that advice might be.

File: akka-http-core/src/main/scala/akka/http/scaladsl/model/headers/headers.scala (hunk 1 above)
Comment (guntiso) [reply akka-http-core/src/main/scala/akka/http/scaladsl/model/headers/headers.scala:468]: .exists(!safeChars(_)) ?

File: akka-http-core/src/main/scala/akka/http/scaladsl/model/headers/headers.scala (hunk 2 above)
Comment (guntiso) [reply akka-http-core/src/main/scala/akka/http/scaladsl/model/headers/headers.scala:470]: > if filename exists and contains unsafe chars => also render filename*

This is because of the decision to hide `filename*` as implementation detail and put unicode under `filename` key in model. Then spec requires to render `filename*`

> if explicit filename* exists => don't generate filename* automatically

This is to allow control over ascii `filename` without resorting to `RawHeader`. For example, provide `"telephone"` instead of default `"t?l?phone"` (derived automatically from `"téléphone"`). It would also be expected to correctly render parameters mentioned in spec.

File: akka-http-core/src/main/scala/akka/http/scaladsl/model/headers/headers.scala (hunk 4 above)
Comment (guntiso) [reply akka-http-core/src/main/scala/akka/http/scaladsl/model/headers/headers.scala:478]: > So, we always render UTF-8, sounds reasonable.

This is according to spec - https://tools.ietf.org/html/rfc8187#section-3.2.1 says:
> Producers MUST use the "UTF-8" ([RFC3629]) character encoding. Extension character encodings (mime-charset) are reserved for future use.

File: akka-http-core/src/main/scala/akka/http/scaladsl/model/headers/headers.scala (hunk 2 above)
Comment (jrudolph) [reply akka-http-core/src/main/scala/akka/http/scaladsl/model/headers/headers.scala:470]: > This is because of the decision to hide `filename*` as implementation detail and put unicode under `filename` key in model. Then spec requires to render `filename*`

Makes sense.

> > if explicit filename* exists => don't generate filename* automatically
> 
> This is to allow control over ascii `filename` without resorting to `RawHeader`. For example, to provide `"telephone"` instead of default `"t?l?phone"` (derived automatically from `"téléphone"`). It would also be expected behaviour to correctly render both parameters mentioned in spec, if provided explicitly.

I agree, that's nice when needed.

File: akka-http-core/src/test/scala/akka/http/impl/model/parser/HttpHeaderSpec.scala [hunk 6]
```diff
@@ -196,6 +196,28 @@ class HttpHeaderSpec extends AnyFreeSpec with Matchers {
         `Content-Disposition`(ContentDispositionTypes.attachment, Map("filename" -> "file/txt", "name" -> "field1"))
       "Content-Disposition: attachment; name=\"field1\"; other=\"\"" =!=
         `Content-Disposition`(ContentDispositionTypes.attachment, Map("name" -> "field1", "other" -> ""))
+      "Content-Disposition: attachment; filename=\"x=2*2+1(?)\"; filename*=UTF-8''x%3D2%2A2+1%28%E2%82%AC%29" =!=
```
Comment (jrudolph) [inline akka-http-core/src/test/scala/akka/http/impl/model/parser/HttpHeaderSpec.scala:199]: Is there a rule in which order `filename` and `filename*` should appear in the parameter list? Because currently the "accidental" solution seems to be that the last `filename` parameter "wins" (probably due to the `TreeMap` constructor in https://github.com/akka/akka-http/pull/3705/files#diff-ad128a726c2bd0651c962a329a9b0d62d2e763a6d76fc3fa5b96cf7084f3173bR23).

If there's no strict rule, could you also add tests going the other way round? I suspect they might be failing ("filename" value overwrites "filename*") in which case we need a smarter resolution rule in the parser.

Comment (guntiso) [reply akka-http-core/src/test/scala/akka/http/impl/model/parser/HttpHeaderSpec.scala:199]: I think `TreeMap` was used to handle rendering, but I do not know the reasoning behind "last parameter wins" in parser. This should be fixed, too.

File: akka-http-core/src/main/scala/akka/http/impl/model/parser/ContentDispositionHeader.scala [hunk 7]
```diff
@@ -20,7 +20,13 @@ private[parser] trait ContentDispositionHeader { this: Parser with CommonRules w
 
   // http://tools.ietf.org/html/rfc6266#section-4.1
   def `content-disposition` = rule {
-    `disposition-type` ~ zeroOrMore(ws(';') ~ `disposition-parm`) ~ EOI ~> (p => TreeMap(p: _*)) ~> (`Content-Disposition`(_, _))
+    `disposition-type` ~ zeroOrMore(ws(';') ~ `disposition-parm`) ~ EOI ~> { p =>
+      val all = TreeMap(p: _*)
+      // https://tools.ietf.org/html/rfc6266#section-4.3
+      // when both "filename" and "filename*" are present in a single header field value,
+      //   recipients SHOULD pick "filename*" and ignore "filename"
```
Comment (jrudolph) [inline akka-http-core/src/main/scala/akka/http/impl/model/parser/ContentDispositionHeader.scala:27]: Great, thanks for looking that up.

File: akka-http-core/src/main/scala/akka/http/scaladsl/model/headers/headers.scala (hunk 1 above)
Comment (jrudolph) [reply akka-http-core/src/main/scala/akka/http/scaladsl/model/headers/headers.scala]: Ah, yes, indeed :)

File: akka-http-core/src/test/scala/akka/http/impl/model/parser/HttpHeaderSpec.scala (hunk 6 above)
Comment (jrudolph) [reply akka-http-core/src/test/scala/akka/http/impl/model/parser/HttpHeaderSpec.scala:199]: Thanks

**Review by jrudolph — APPROVED** [review]
LGTM, thanks a lot, @guntiso, that has been a long-standing issue now finally fixed!
