### PR TITLE
core: don't fail slot after previous connection failed in special condition

### LINKED ISSUE #1439: "Connection reset by peer" during file upload
Akka server randomly fails with connection rest by peer during uploads if response is sent before all chunks are processed. For example when entity size limit is reached. Similar problems can be observed if upload is done through browser, sometimes response is sent, sometimes browser waits for full upload, sometimes connection is closed. I think I managed to isolate the problem and there is code to do that:  

```
[debug]   Classpath:
[debug] 	/tmp/sbt_c914386c/job-1/target/f6620d8f/con_test_2.12-0.1-SNAPSHOT.jar
[debug] 	/tmp/sbt_c914386c/target/f2e496f2/scala-library.jar
[debug] 	/tmp/sbt_c914386c/target/437cfe40/akka-actor_2.12-2.5.4.jar
[debug] 	/tmp/sbt_c914386c/target/2cf7a6cc/config-1.3.1.jar
[debug] 	/tmp/sbt_c914386c/target/1e6f1e74/scala-java8-compat_2.12-0.8.0.jar
[debug] 	/tmp/sbt_c914386c/target/395605a0/akka-http-spray-json_2.12-10.0.10.jar
[debug] 	/tmp/sbt_c914386c/target/4cbea03a/akka-http_2.12-10.0.10.jar
[debug] 	/tmp/sbt_c914386c/target/eb51e977/akka-http-core_2.12-10.0.10.jar
[debug] 	/tmp/sbt_c914386c/target/b6ba857b/akka-parsing_2.12-10.0.10.jar
[debug] 	/tmp/sbt_c914386c/target/af1a9f8f/akka-stream_2.12-2.5.4.jar
[debug] 	/tmp/sbt_c914386c/target/1b1c9116/reactive-streams-1.0.1.jar
[debug] 	/tmp/sbt_c914386c/target/7497c001/ssl-config-core_2.12-0.2.1.jar
[debug] 	/tmp/sbt_c914386c/target/7c5f25a2/scala-parser-combinators_2.12-1.0.4.jar
[debug] 	/tmp/sbt_c914386c/target/6e01a672/spray-json_2.12-1.3.3.jar
[debug] 	/tmp/sbt_c914386c/target/457bfc65/akka-http-xml_2.12-10.0.10.jar
[debug] 	/tmp/sbt_c914386c/target/e22de336/scala-xml_2.12-1.0.6.jar
[debug] 	/tmp/sbt_c914386c/target/b5d88662/akka-slf4j_2.12-2.5.4.jar
[debug] 	/tmp/sbt_c914386c/target/432be7c9/slf4j-api-1.7.23.jar
[debug] Waiting for thread run-main-0 to terminate.

```

Sample code to reproduce bug: 

```
import akka.actor.ActorSystem
import akka.http.scaladsl.Http
import akka.http.scaladsl.model.HttpEntity.{Chunk, Chunked}
import akka.http.scaladsl.model._
import akka.http.scaladsl.server.Directives._
import akka.http.scaladsl.server.{ExceptionHandler, Route}
import akka.stream.{ActorMaterializer, Materializer}
import akka.stream.scaladsl.{Sink, Source}

import scala.concurrent.Await
import scala.concurrent.duration._
import scala.util.{Failure, Random, Success}

object ConnectionResetByPeerTest extends scala.App{
  implicit val system = ActorSystem("test-system")
  implicit val materializer: Materializer = ActorMaterializer()
  implicit val executor = system.dispatcher

  def entityStreamSizeExceptionHandler = ExceptionHandler {
    case _: EntityStreamSizeException => complete(StatusCodes.RequestEntityTooLarge)
  }

  val uploadSizeLimit = 1024 * 1024
  def upload: Route = handleExceptions(entityStreamSizeExceptionHandler){
    (post & path("upload")){
      withSizeLimit(uploadSizeLimit){
        extractRequestContext { ctx =>
          complete(ctx.request.entity.dataBytes.runWith(Sink.ignore).map(_ => StatusCodes.OK))
        }
      }
    }
  }

  val bind = Await.ready(Http().bindAndHandle( upload, "0.0.0.0", 8080), 1 minute)

  val flow = Http().superPool[Unit]()

  val chunkCount = 20000
  (1 to 10000) foreach { i=>
    val chunk = Chunk(Random.alphanumeric.take(100000).mkString)
    val source = Source(List.fill(chunkCount)(chunk))
    val entity = Chunked(ContentTypes.`text/plain(UTF-8)`, source)

    println("===========================")
    println("Iteration: "+i)
    println("===========================")

    val request = HttpRequest(method = HttpMethods.POST, uri = "http://localhost:8080/upload", entity = entity)
    val responseFuture = Source.single(request -> ((): Unit)).via(flow).completionTimeout(1 minute).runWith(Sink.head)

    Await.ready(responseFuture.map(_._1), 1 minute).value.map(r => r.flatten) match {
      case Some(Success(result)) => result
      case Some(Failure(error)) => throw new AssertionError(error)
      case None => sys.error("Future reached timeout ")
    }

  }

  bind.foreach(_.unbind())
  println("DONE")
}
```
Error: 

```
[INFO] [09/25/2017 12:37:03.024] [test-system-akka.actor.default-dispatcher-23] [akka://test-system/system/IO-TCP/selectors/$a/19] Message [akka.io.Tcp$Write] from Actor[akka://test-system/user/StreamSupervisor-1/$$j#1726155251] to Actor[akka://test-system/system/IO-TCP/selectors/$a/19#229162384] was not delivered. [6] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
===========================
Iteration: 11
===========================
[INFO] [09/25/2017 12:37:03.053] [test-system-akka.actor.default-dispatcher-3] [akka://test-system/system/IO-TCP/selectors/$a/21] Message [akka.io.Tcp$Write] from Actor[akka://test-system/user/StreamSupervisor-1/$$k#-874021409] to Actor[akka://test-system/system/IO-TCP/selectors/$a/21#1225581899] was not delivered. [7] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
===========================
Iteration: 12
===========================
===========================
Iteration: 13
===========================
[error] (run-main-0) java.lang.AssertionError: akka.stream.StreamTcpException: The connection closed with error: Connection reset by peer
[error] java.lang.AssertionError: akka.stream.StreamTcpException: The connection closed with error: Connection reset by peer
[error] 	at ConnectionResetByPeerTest$.$anonfun$new$1(ConnectionResetByPeerTest.scala:54)
[error] 	at ConnectionResetByPeerTest$.$anonfun$new$1$adapted(ConnectionResetByPeerTest.scala:40)
[error] 	at scala.collection.immutable.Range.foreach(Range.scala:156)
[error] 	at ConnectionResetByPeerTest$.delayedEndpoint$ConnectionResetByPeerTest$1(ConnectionResetByPeerTest.scala:40)
[error] 	at ConnectionResetByPeerTest$delayedInit$body.apply(ConnectionResetByPeerTest.scala:15)
[error] 	at scala.Function0.apply$mcV$sp(Function0.scala:34)
[error] 	at scala.Function0.apply$mcV$sp$(Function0.scala:34)
[error] 	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
[error] 	at scala.App.$anonfun$main$1$adapted(App.scala:76)
[error] 	at scala.collection.immutable.List.foreach(List.scala:389)
[error] 	at scala.App.main(App.scala:76)
[error] 	at scala.App.main$(App.scala:74)
[error] 	at ConnectionResetByPeerTest$.main(ConnectionResetByPeerTest.scala:15)
[error] 	at ConnectionResetByPeerTest.main(ConnectionResetByPeerTest.scala)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.lang.reflect.Method.invoke(Method.java:498)
[error] 	at sbt.Run.invokeMain(Run.scala:89)
[error] 	at sbt.Run.run0(Run.scala:83)
[error] 	at sbt.Run.execute$1(Run.scala:61)
[error] 	at sbt.Run.$anonfun$run$4(Run.scala:73)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] 	at sbt.util.InterfaceUtil$$anon$1.get(InterfaceUtil.scala:10)
[error] 	at sbt.TrapExit$App.run(TrapExit.scala:252)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] Caused by: akka.stream.StreamTcpException: The connection closed with error: Connection reset by peer
[debug] 	Thread run-main-0 exited.
[debug] Waiting for thread test-system-akka.actor.default-blocking-io-dispatcher-10 to terminate.

```

### PR DESCRIPTION
**Pull request by jrudolph**
The special condition is that the previous request got an early response and
the connection afterwards broke while waiting for the rest of the request.

Fixes #1439

### CODE REVIEW

File: akka-http-core/src/main/scala/akka/http/impl/engine/client/pool/NewHostConnectionPool.scala [hunk 1]
```diff
@@ -257,6 +257,7 @@ private[client] object NewHostConnectionPool {
 
                 debug(s"Before event [${event.name}] In state [${state.name}] for [${timeInState / 1000000} ms]")
                 state = event.transition(state, this, arg)
+                require(state != Unconnected, "Slot must not change to Unconnected state") // Use ToBeClosed or Failed instead from state impls
```
Comment (jrudolph) [inline akka-http-core/src/main/scala/akka/http/impl/engine/client/pool/NewHostConnectionPool.scala]: The state machine has become quite complicated once again with these kind of barely documented assumptions behind it.
