### PR TITLE
Handle stream cancellation while outgoing data is buffered 

### LINKED ISSUE #2236: Http/2 connection (stream?) may fail with an assertion if a sendable stream is cancelled while stream data is waiting for being sent out
As reported in https://github.com/akka/akka-grpc/issues/357.

Exception:

```
java.lang.IllegalArgumentException: requirement failed
	at scala.Predef$.require(Predef.scala:264)
	at akka.http.impl.engine.http2.Http2MultiplexerSupport$$anon$1$WithSendableOutStreams.sendNext(Http2Multiplexer.scala:301)
	at akka.http.impl.engine.http2.Http2MultiplexerSupport$$anon$1$WaitingForNetworkToSendData.onPull(Http2Multiplexer.scala:315)
	at akka.http.impl.engine.http2.Http2MultiplexerSupport$$anon$1.onPull(Http2Multiplexer.scala:225)
	at akka.stream.impl.fusing.GraphInterpreter.processPull(GraphInterpreter.scala:526)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:422)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:588)
	at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:472)
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:563)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:745)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:760)
	at akka.actor.Actor.aroundReceive(Actor.scala:517)
	at akka.actor.Actor.aroundReceive$(Actor.scala:515)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:670)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:588)
	at akka.actor.ActorCell.invoke(ActorCell.scala:557)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
	at akka.dispatch.Mailbox.run(Mailbox.scala:225)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

### PR DESCRIPTION
**Pull request by johanandren**
Fixes #2236

### CODE REVIEW

File: akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ServerSpec.scala [hunk 1]
```diff
@@ -347,6 +347,18 @@ class Http2ServerSpec extends AkkaSpec("""
         sendRST_STREAM(TheStreamId, ErrorCode.CANCEL)
         entityDataOut.expectCancellation()
       }
+
+      "handle RST_STREAM while data is in buffer" in new WaitingForResponseDataSetup {
```
Comment (johanandren) [inline akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ServerSpec.scala]: I found it hard to describe in a clear way the exact scenario is. Ideas?

File: akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2Multiplexer.scala [hunk 2]
```diff
@@ -335,6 +348,14 @@ private[http2] trait Http2MultiplexerSupport { logic: GraphStageLogic with Stage
         def enqueueOutStream(outStream: OutStream): Unit =
           if (!sendableOutstreams.contains(outStream.streamId))
             become(copy(sendableOutstreams = sendableOutstreams + outStream.streamId))
+
+        def closeStream(outStream: OutStream): Unit =
```
Comment (jrudolph) [inline akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2Multiplexer.scala]: Can you also add a test case for this scenario? You will have to exhaust the connection window before it ends up here but there should already be tests doing that.

File: akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2Multiplexer.scala [hunk 3]
```diff
@@ -335,6 +348,14 @@ private[http2] trait Http2MultiplexerSupport { logic: GraphStageLogic with Stage
...
+          if (sendableOutstreams.contains(outStream.streamId)) {
+            val sendableExceptClosed = sendableOutstreams - outStream.streamId
+
+            if (sendableExceptClosed.isEmpty) become(Idle)
+            else become(WaitingForNetworkToSendData(sendableExceptClosed))
```
Comment (jrudolph) [inline akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2Multiplexer.scala]: Is that really correct? Shouldn't it stay in this state?

File: akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2Multiplexer.scala (hunk 2 above)
Comment (jrudolph) [inline akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2Multiplexer.scala]: DRY up with the above?

File: akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ServerSpec.scala (hunk 1 above)
Comment (jrudolph) [reply akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ServerSpec.scala]: Sounds pretty good, maybe "while data is waiting in outgoing stream buffer"

File: akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ServerSpec.scala [hunk 4]
```diff
@@ -347,6 +347,18 @@ class Http2ServerSpec extends AkkaSpec("""
...
+        val data1 = ByteString("abcd")
+        entityDataOut.sendNext(data1)
+
+        sendRST_STREAM(TheStreamId, ErrorCode.CANCEL)
+        // pull the network (in reality the bug #2236 only happens with more than one stream, this is the minimal repeater)
+        toNet.request(9)
+        toNet.expectNoBytes()
```
Comment (jrudolph) [inline akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ServerSpec.scala]: :+1:

File: akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2Multiplexer.scala [hunk 5]
```diff
@@ -111,6 +111,7 @@ private[http2] trait Http2MultiplexerSupport { logic: GraphStageLogic with Stage
           buffer = ByteString.empty
           trailer = None
           maybeInlet.foreach(_.cancel())
+          state.closeStream(this)
```
Comment (jrudolph) [inline akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2Multiplexer.scala]: Maybe also add a forwarder in the parent class to avoid accessing `state` from inside here. (Not a real problem just to make it consistent with the other code).

File: akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ServerSpec.scala [hunk 6]
```diff
@@ -347,6 +347,32 @@ class Http2ServerSpec extends AkkaSpec("""
...
+        entityDataOut.expectCancellation()
+      }
+
+      "handle RST_STREAM while waiting for a window update" in new WaitingForResponseDataSetup {
+        entityDataOut.sendNext(bytes(70000, 0x23)) // 70000 > Http2Protocol.InitialWindowSize
+        expectDATA(TheStreamId, false, Http2Protocol.InitialWindowSize)
+
+        expectNoBytes()
+
+        sendWINDOW_UPDATE(TheStreamId, 10000) // > than the remaining bytes (70000 - InitialWindowSize)
```
[the remark this answers is not in the document]
Comment (jrudolph) [reply akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ServerSpec.scala]: Any good observation, something smells like a bug here.

[the remark this answers is not in the document]
Comment (jrudolph) [reply akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ServerSpec.scala]: Ah, wait makes sense, of course (but I didn't explain it when we talked about it): there's both connection-level and stream-level windows. `WaitingForConnectionWindow` is only reached if a stream is allowed to send (i.e. stream-level window is big enough) but nothing can be sent on the connection level. That's why you need that extra WINDOW_UPDATE which works on the stream level to get into that state.
