### PR TITLE
=ht2,htc #1160 #1159 fix preview settings

### LINKED ISSUE #1159: Configuring HTTP2 support is hard because of missing `withXXX` methods and missing overloads for scaladsl
This should compile:

```scala
import akka.http.scaladsl.settings.ServerSettings
  import akka.http.scaladsl.settings.PreviewServerSettings
  val serverSettings: ServerSettings =
    ServerSettings(system)
      .withPreviewServerSettings(PreviewServerSettings(system).withEnableHttp2(true))
      .withRemoteAddressHeader(true)
```

Also following code fails at runtime because companion object is created with wrong config path:

```scala
PreviewServerSettings(system)
```

### LINKED ISSUE #1160: Http2: RemoteAddress setting not working for HTTP/1 behind ALPNSwitch
The reason is that the settings are not passed to the HTTP1 `serverLayer` here: https://github.com/akka/akka-http/blob/2e0d2b5b219c21ce3acd1ced0cb2a2e7cd6aa1ee/akka-http2-support/src/main/scala/akka/http/scaladsl/Http2.scala#L79-L79

### PR DESCRIPTION
**Pull request by ktoso**
Resolves #1159
Resolves #1160 ~(though I don't think it was the bug)~

### CODE REVIEW

File: akka-http2-support/src/main/scala/akka/http/scaladsl/Http2.scala [hunk 1]
```diff
@@ -76,7 +76,7 @@ class Http2Ext(private val config: Config)(implicit val system: ActorSystem)
       }
       val tls = TLS(createEngine, _ ⇒ Success(()), IgnoreComplete)
 
-      AlpnSwitch(getChosenProtocol, Http().serverLayer(), http2Layer()) atop
+      AlpnSwitch(getChosenProtocol, http.serverLayer(), http2Layer()) atop
```
Comment (2m) [inline akka-http2-support/src/main/scala/akka/http/scaladsl/Http2.scala]: Wasn't the @jrudolph comment here https://github.com/akka/akka-http/issues/1160#issue-231293957 about passing settings to `serverLayer` like so:

```scala
serverLayer(settings = settings)
```

**Comment by ktoso** [comment]
Failure was unrelated and known: https://github.com/akka/akka-http/issues/1061

File: akka-http2-support/src/main/scala/akka/http/scaladsl/Http2.scala (hunk 1 above)
Comment (jrudolph) [inline akka-http2-support/src/main/scala/akka/http/scaladsl/Http2.scala]: Yep, thanks for the extra eyes @2m.
