### PR TITLE
=htc #1786 fix customMediaTypes behavior

### LINKED ISSUE #1786: Enabling ParsingSettings.customMediaTypes breaks predefined media type parsing
In the following code snippet `ParsingSettings.customMediaTypes` is compared to a somewhat arbitrary value to check if behavior should be enabled or not. This is fine as an optimization but providing an equivalent function should not change the behavior. 

https://github.com/akka/akka-http/blob/3c966af2255b58b02fbdacd6abec89c47f78ce48/akka-http-core/src/main/scala/akka/http/impl/model/parser/CommonActions.scala#L59

Providing an equivalent function (i.e. one that always returns `None`) makes RequestParserCRLFSpec and many other tests fail.

This was discovered while migrating `akka.stream.impl.ConstantFun`  to `akka.util.ConstantFun`.

### PR DESCRIPTION
**Pull request by jrudolph**
Previously, defining customMediaType in ParserSettings broke parsing of
predefined media types or custom ad-hoc media-types with charsets. This had
two reasons:

 * when custom media types were defined, we never parsed into our own
   predefined ones any more
 * areCustomMediaTypesDefined was defined the wrong way round: just checking
   that the value was changed from the magic one doesn't mean there might
   still be none defined

Fixes #1786.

### CODE REVIEW

File: akka-http-core/src/main/scala/akka/http/impl/model/parser/CommonActions.scala [hunk 1]
```diff
@@ -33,29 +32,27 @@ private[parser] trait CommonActions {
...
-          customMediaTypes(mainLower, subType) getOrElse fallbackMediaType(subType, params, mainLower)
-        else MediaTypes.getForKey((mainLower, subLower)) match {
-          case Some(registered) ⇒ if (params.isEmpty) registered else registered.withParams(params)
-          case None ⇒
-            if (charsetDefined)
-              MediaType.customWithOpenCharset(mainLower, subType, params = params, allowArbitrarySubtypes = true)
-            else
-              fallbackMediaType(subType, params, mainLower)
-        }
+        if (areNoCustomMediaTypesDefined) // try to prevent closure creation for usual case without custom media types
```
Comment (ktoso) [inline akka-http-core/src/main/scala/akka/http/impl/model/parser/CommonActions.scala]: good
