### PR TITLE
docs: fix HttpServerWithTypedSample compilation against 2.6

### LINKED ISSUE #2936: Failed: compilation against Akka master branch
Compilation against Akka master was accidentally disabled for a long time. A recent build showed compilation errors:

https://jenkins.akka.io:8498/job/akka-http-nightly/AKKA_VERSION=master,Node=akka-http-nightly-node,SCALA_VERSION=2.12.10,jdk=AdoptOpenJDK%208/4/consoleFull

```
[error] /home/jenkins/workspace/workspace/akka-http-nightly/AKKA_VERSION/master/Node/akka-http-nightly-node/SCALA_VERSION/2.12.10/jdk/AdoptOpenJDK 8/docs/src/test/scala/docs/http/scaladsl/HttpServerWithTypedSample.scala:116:43: ambiguous implicit values:
[error]  both value scheduler in class JobRoutes of type => akka.actor.typed.Scheduler
[error]  and method schedulerFromActorSystem in object AskPattern of type (implicit system: akka.actor.typed.ActorSystem[_])akka.actor.typed.Scheduler
[error]  match expected type akka.actor.typed.Scheduler
[error]                     buildJobRepository.ask(JobRepository.AddJob(job, _))
[error]                                           ^
[error] /home/jenkins/workspace/workspace/akka-http-nightly/AKKA_VERSION/master/Node/akka-http-nightly-node/SCALA_VERSION/2.12.10/jdk/AdoptOpenJDK 8/docs/src/test/scala/docs/http/scaladsl/HttpServerWithTypedSample.scala:125:41: ambiguous implicit values:
[error]  both value scheduler in class JobRoutes of type => akka.actor.typed.Scheduler
[error]  and method schedulerFromActorSystem in object AskPattern of type (implicit system: akka.actor.typed.ActorSystem[_])akka.actor.typed.Scheduler
[error]  match expected type akka.actor.typed.Scheduler
[error]                   buildJobRepository.ask(JobRepository.ClearJobs(_))
[error]                                         ^
[error] /home/jenkins/workspace/workspace/akka-http-nightly/AKKA_VERSION/master/Node/akka-http-nightly-node/SCALA_VERSION/2.12.10/jdk/AdoptOpenJDK 8/docs/src/test/scala/docs/http/scaladsl/HttpServerWithTypedSample.scala:135:37: ambiguous implicit values:
[error]  both value scheduler in class JobRoutes of type => akka.actor.typed.Scheduler
[error]  and method schedulerFromActorSystem in object AskPattern of type (implicit system: akka.actor.typed.ActorSystem[_])akka.actor.typed.Scheduler
[error]  match expected type akka.actor.typed.Scheduler
[error]               buildJobRepository.ask(JobRepository.GetJobById(id, _))
[error]
```

### PR DESCRIPTION
**Pull request by jrudolph**
Fixes #2936

### CODE REVIEW

File: docs/src/test/scala/docs/http/scaladsl/HttpServerWithTypedSample.scala [hunk 1]
```diff
@@ -96,13 +96,13 @@ object HttpServerWithTypedSample {
 
   class JobRoutes(buildJobRepository: ActorRef[JobRepository.Command])(implicit system: ActorSystem[_]) extends JsonSupport {
 
-    import akka.actor.typed.scaladsl.AskPattern._
```
Comment (jrudolph) [inline docs/src/test/scala/docs/http/scaladsl/HttpServerWithTypedSample.scala]: This import introduces an ambiguity with the below explicit implicit.
