### PR TITLE
Ignore case for MediaType.hashCode

### LINKED ISSUE #2144: MediaType discrepency between hashCode and equals: cannot use Set
Media types are case insensitive. Currently, `MediaType`'s [equals](https://github.com/akka/akka-http/blob/f3e83935ffc27bc94f586d9387b54b499c6250d4/akka-http-core/src/main/scala/akka/http/scaladsl/model/MediaType.scala#L53) method correctly ignores case, but its [hashCode](https://github.com/akka/akka-http/blob/f3e83935ffc27bc94f586d9387b54b499c6250d4/akka-http-core/src/main/scala/akka/http/scaladsl/model/MediaType.scala#L59) is calculated on the raw value. This presents a problem for when parsed incoming media types are looked up in a `HashSet` or `HashMap`: since the hash codes differ for differently-cased `MediaType` instances for the same media type, the set will look in the wrong bucket and not ever invoke `equals()`. 

I think a simple fix could be to change `hashCode()` to be `value.toLowerCase().hashCode()` and perhaps cache that.

### PR DESCRIPTION
**Pull request by jypma**
If MediaType instances are used with a hashset or hashmap,
equivalent (equal) objects should go into the same buckets. Since
MediaType's equals() method correctly is case insensitive, do should its
hashCode.

Fixes #2144.

### CODE REVIEW

**Comment by raboof** [comment]
PLS BUILD

**Comment by ktoso** [comment]
Thanks!

File: akka-http-core/src/main/scala/akka/http/scaladsl/model/MediaType.scala [hunk 1]
```diff
@@ -56,7 +56,7 @@ sealed abstract class MediaType extends jm.MediaType with LazyValueBytesRenderab
       case _            ⇒ false
     }
 
-  override def hashCode(): Int = value.hashCode
+  override def hashCode(): Int = value.toLowerCase.hashCode
```
Comment (hepin1989) [inline akka-http-core/src/main/scala/akka/http/scaladsl/model/MediaType.scala]: val

Comment (ktoso) [reply akka-http-core/src/main/scala/akka/http/scaladsl/model/MediaType.scala]: Nah, def is fine. No reason to increase the weight of the object for this
