### PR TITLE
Fix directory traversal in Windows in getFromDirectory / listDirectoryContents

### LINKED ISSUE #346: Directory Traversal Attack vulnerability in Akka HTTP's getFrom(Browseable)Directory directive
I noticed that when running Akka HTTP server in Windows machine I am able to access all files of the server machine.

**Example**

With route:
`
pass {
   getFromBrowseableDirectory("/some/directory/i/only/want/to/share")
}
`
or
`
pass {
   getFromDirectory("/some/directory/i/only/want/to/share")
}
`

I can request for example:
http://localhost:8080/%5c..%5c..%5c..%5c..%5c..%5c..%5c..%5c..%5c..%5cwindows/win.ini
...and download the actual win.ini file that exist in C:/windows

In the case of getFromBrowseableDirectory I can also see all the files there is in the server machine.

That is Directory Traversal Attack vulnerability: https://www.owasp.org/index.php/Path_Traversal

### PR DESCRIPTION
**Pull request by jrudolph**
@2beaucoup here's a new fix without all your extra changes. AFAICS these should apply also to former versions for which we might have to issue a fix release.

WDYT about containing the changes inside of the new `safeDirectoryChildPath` (old `fileSystemPath`)?

Fixes #346.

### CODE REVIEW

**Comment by jrudolph** [comment]
We should follow this up with your other changes for modernizing the infrastructure to java.nio.file.

**Comment by 2beaucoup** [comment]
Looks good @jrudolph. A bit sad that that we have to resort to basic string matching.

It's just the nio stuff that's missing here, right?

File: akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/FileAndResourceDirectivesSpec.scala [hunk 1]
```diff
@@ -27,7 +27,8 @@ class FileAndResourceDirectivesSpec extends RoutingSpec with Inspectors with Ins
   // operations touch files, can be randomly hit by slowness
   implicit val routeTestTimeout = RouteTestTimeout(3.seconds)
 
-  val testRoot = new File(getClass.getClassLoader.getResource("").toURI)
+  val testRoot = new File("akka-http-tests/src/test/resources")
+  require(testRoot.exists(), s"testRoot was not found at ${testRoot.getAbsolutePath}")
```
Comment (2beaucoup) [inline akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/FileAndResourceDirectivesSpec.scala]: Why hardcode the `testRoute` path?

Comment (jrudolph) [inline akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/FileAndResourceDirectivesSpec.scala]: Because, otherwise, files will be served from the `target` directory where sbt will have copied all files over, resolving symlinks in the process.

**Comment by jrudolph** [comment]
> A bit sad that that we have to resort to basic string matching.

Yes, but it's only for this version. We should still fix it using the nio stuff in the end. I'd just like to keep the actual fix small for now and compatible to older versions.

> It's just the nio stuff that's missing here, right?

Yes, basically all your cleanups are still missing (but still highly appreciated). If you'd like you could port them over in a new PR, otherwise, I'd try to do it when I get to it (but this might take a while because of upcoming traveling next week).

File: akka-http/src/main/scala/akka/http/scaladsl/server/directives/FileAndResourceDirectives.scala [hunk 2]
```diff
@@ -217,14 +217,33 @@ object FileAndResourceDirectives extends FileAndResourceDirectives {
       BasicDirectives.extractSettings
 
   private def withTrailingSlash(path: String): String = if (path endsWith "/") path else path + '/'
-  private def fileSystemPath(base: String, path: Uri.Path, log: LoggingAdapter, separator: Char = File.separatorChar): String = {
+
+  /**
+   * Given a base directory and a (Uri) path, returns a path to a location contained in the base directory,
+   * while checking that no path traversal is possible. Path traversable is prevented by two individual measures:
```
Comment (ktoso) [inline akka-http/src/main/scala/akka/http/scaladsl/server/directives/FileAndResourceDirectives.scala]: Path traversable is prev => Path traversabl is prev

File: akka-http/src/main/scala/akka/http/scaladsl/server/directives/FileAndResourceDirectives.scala [hunk 3]
```diff
@@ -217,14 +217,33 @@ object FileAndResourceDirectives extends FileAndResourceDirectives {
...
+   *  - A path segment must not be ".." and must not contain slashes or backslashes that may carry special meaning in
+   *    file-system paths. This logic is intentionally a bit conservative as it might also prevent legitimate access
```
Comment (ktoso) [inline akka-http/src/main/scala/akka/http/scaladsl/server/directives/FileAndResourceDirectives.scala]: good

File: akka-http/src/main/scala/akka/http/scaladsl/server/directives/FileAndResourceDirectives.scala [hunk 4]
```diff
@@ -217,14 +217,33 @@ object FileAndResourceDirectives extends FileAndResourceDirectives {
...
+
+  private def safeJoinPaths(base: String, path: Uri.Path, log: LoggingAdapter, separator: Char = File.separatorChar): String = {
     import java.lang.StringBuilder
     @tailrec def rec(p: Uri.Path, result: StringBuilder = new StringBuilder(base)): String =
       p match {
         case Uri.Path.Empty       ⇒ result.toString
         case Uri.Path.Slash(tail) ⇒ rec(tail, result.append(separator))
         case Uri.Path.Segment(head, tail) ⇒
-          if (head.indexOf('/') >= 0 || head == "..") {
+          if (head.indexOf('/') >= 0 || head.indexOf('\\') >= 0 || head == "..") {
```
Comment (ktoso) [inline akka-http/src/main/scala/akka/http/scaladsl/server/directives/FileAndResourceDirectives.scala]: good

File: akka-http/src/main/scala/akka/http/scaladsl/server/directives/FileAndResourceDirectives.scala [hunk 5]
```diff
@@ -233,6 +252,24 @@ object FileAndResourceDirectives extends FileAndResourceDirectives {
...
+   */
+  private def checkIsSafeDescendant(basePath: String, finalPath: String, log: LoggingAdapter): String = {
+    val baseFile = new File(basePath)
+    val finalFile = new File(finalPath)
+    val canonicalFinalPath = finalFile.getCanonicalPath
+
+    if (!canonicalFinalPath.startsWith(baseFile.getCanonicalPath)) {
+      log.warning(s"[$finalFile] points to a location that is not part of [$baseFile]. This might be a directory " +
+        "traversal attempt.")
+      ""
```
Comment (ktoso) [inline akka-http/src/main/scala/akka/http/scaladsl/server/directives/FileAndResourceDirectives.scala]: why "" and not throwing here?

File: akka-http/src/main/scala/akka/http/scaladsl/server/directives/FileAndResourceDirectives.scala (hunk 2 above)
Comment (jrudolph) [inline akka-http/src/main/scala/akka/http/scaladsl/server/directives/FileAndResourceDirectives.scala]: Thanks ;)

File: akka-http/src/main/scala/akka/http/scaladsl/server/directives/FileAndResourceDirectives.scala (hunk 5 above)
Comment (jrudolph) [inline akka-http/src/main/scala/akka/http/scaladsl/server/directives/FileAndResourceDirectives.scala]: I just kept the previous behavior of just rejecting the request.

Comment (jrudolph) [inline akka-http/src/main/scala/akka/http/scaladsl/server/directives/FileAndResourceDirectives.scala]: Otherwise, there might be a higher risk of revealing some information if the response is not the same as if the file is just missing.

Comment (ktoso) [inline akka-http/src/main/scala/akka/http/scaladsl/server/directives/FileAndResourceDirectives.scala]: I see, that makes sense. Information exposure would be bad too

**Comment by jrudolph** [comment]
Merged. Thanks a lot again @2beaucoup.

**Comment by 2beaucoup** [comment]
👍 I'll close the other one then.

**Comment by jrudolph** [comment]
Backport to old repo (akka 2.4.x): https://github.com/akka/akka/pull/21584
Backport to stream-http-2.0: https://github.com/akka/akka/pull/21586
