### PR TITLE
Revamp SPI / API of ClientTransport infrastructure to fix #1012 and to simplify API

### LINKED ISSUE #1012: idle-timeout became broken between 10.0.4 and 10.0.5?
It seems we may have broken idle timeouts in 10.0.5, I will look into this immediately,

Notes: 

> It appears that this might indeed be a bug introduced during a change to make the transport API more pluggable. You can see that in v10.0.4 Tcp().outgoingConnection explicitly sets the idleTimeout, whereas in the current master it relies on that to be set by the passed in, pluggable transport. This would be ok as @ClientTransport.TCPTransport utilizes the passed in idleTimeout which the transport is utilized by the PoolInterfaceActor after having been created by the ConnectionSettings here. So, all that said, at a fair review it looks like the timeout should still be handled appropriately as everything seems to be instantiated at the correct times. So we will have to dig a bit deeper to determine if and how this pluggable change affected items such as timeout.

### PR DESCRIPTION
**Pull request by jrudolph**
This was inspired by part of @ktoso's fix in #1014 but goes a bit further to simplify the transport API.

A transport is now a static constant function value that gets passed
all parameters at connection time.

That fixes #1012 where client connection settings were both kept redundantly
inside the transport and inside the settings.

It's now also possible to specify the localAddress inside the settings. Methods
in the Http entrypoint that allow specifying the localAddress explicitly will
override whatever was given in the settings. In the future we'd like to
get rid of all those parameters to simplify entrypoint signatures in Http.

There is a basic disadvantage of passing `ClientConnectionSettings` to the `connectTo` method which is that whatever settings future `ClientTransport` come up with, they have to be put into those `ClientConnectionSettings`, so this might become an even bigger grab bag than it is right now.

Fixes #1012.

### CODE REVIEW

**Comment by jrudolph** [comment]
PLS BUILD

File: akka-http-core/src/main/scala/akka/http/scaladsl/ClientTransport.scala [hunk 1]
```diff
@@ -17,23 +17,28 @@ import scala.concurrent.Future
...
+@ApiMayChange
 object ClientTransport {
-  def TCP(localAddress: Option[InetSocketAddress], settings: ClientConnectionSettings): ClientTransport =
-    new TCPTransport(localAddress, settings)
+  val TCP: ClientTransport = TCPTransport
 
-  private case class TCPTransport(localAddress: Option[InetSocketAddress], settings: ClientConnectionSettings) extends ClientTransport {
-    def connectTo(host: String, port: Int)(implicit system: ActorSystem): Flow[ByteString, ByteString, Future[OutgoingConnection]] =
+  private case object TCPTransport extends ClientTransport {
+    def connectTo(host: String, port: Int, settings: ClientConnectionSettings)(implicit system: ActorSystem): Flow[ByteString, ByteString, Future[OutgoingConnection]] =
```
Comment (ktoso) [inline akka-http-core/src/main/scala/akka/http/scaladsl/ClientTransport.scala]: Yeah, this solves the problem of it being passed in "too early and only once", good.

File: akka-http-core/src/main/scala/akka/http/scaladsl/Http.scala [hunk 2]
```diff
@@ -297,7 +297,7 @@ class HttpExt(private val config: Config)(implicit val system: ActorSystem) exte
                          localAddress: Option[InetSocketAddress] = None,
                          settings:     ClientConnectionSettings  = ClientConnectionSettings(system),
                          log:          LoggingAdapter            = system.log): Flow[HttpRequest, HttpResponse, Future[OutgoingConnection]] =
-    _outgoingConnection(host, port, settings, ConnectionContext.noEncryption(), ClientTransport.TCP(localAddress, settings), log)
+    _outgoingConnection(host, port, settings.withLocalAddressOverride(localAddress), ConnectionContext.noEncryption(), ClientTransport.TCP, log)
```
Comment (ktoso) [inline akka-http-core/src/main/scala/akka/http/scaladsl/Http.scala]: good, makes sense; this is where the passing in of the settings previously did not do what was expected AFAIR

File: akka-http-core/src/main/scala/akka/http/scaladsl/settings/ClientConnectionSettings.scala [hunk 3]
```diff
@@ -61,6 +44,15 @@ abstract class ClientConnectionSettings private[akka] () extends akka.http.javad
...
+  def withLocalAddress(newValue: Option[InetSocketAddress]): ClientConnectionSettings = self.copy(localAddress = newValue)
+
+  /**
+   * Returns a new instance with the given local address set if the given override is `Some(address)`, otherwise
+   * return this instance unchanged.
+   */
+  def withLocalAddressOverride(overrideLocalAddressOption: Option[InetSocketAddress]): ClientConnectionSettings =
+    if (overrideLocalAddressOption.isDefined) withLocalAddress(overrideLocalAddressOption)
+    else this
 }
```
Comment (ktoso) [inline akka-http-core/src/main/scala/akka/http/scaladsl/settings/ClientConnectionSettings.scala]: good 👍

File: akka-http-core/src/main/scala/akka/http/scaladsl/settings/ClientConnectionSettings.scala [hunk 4]
```diff
@@ -34,19 +29,7 @@ abstract class ClientConnectionSettings private[akka] () extends akka.http.javad
...
-  final override def getConnectingTimeout: FiniteDuration = connectingTimeout
-  final override def getParserSettings: js.ParserSettings = parserSettings
-  final override def getIdleTimeout: Duration = idleTimeout
-  final override def getSocketOptions: Iterable[SocketOption] = socketOptions.asJava
-  final override def getUserAgentHeader: Optional[UserAgent] = OptionConverters.toJava(userAgentHeader)
-  final override def getLogUnencryptedNetworkBytes: Optional[Int] = OptionConverters.toJava(logUnencryptedNetworkBytes)
-  final override def getRequestHeaderSizeHint: Int = requestHeaderSizeHint
-  final override def getWebsocketRandomFactory: Supplier[Random] = new Supplier[Random] {
-    override def get(): Random = websocketRandomFactory()
-  }
```
Comment (ktoso) [inline akka-http-core/src/main/scala/akka/http/scaladsl/settings/ClientConnectionSettings.scala]: moving them up one level looks good 👍

File: akka-http-core/src/test/scala/akka/http/impl/engine/client/ConnectionPoolSpec.scala [hunk 5]
```diff
@@ -566,4 +591,45 @@ class ConnectionPoolSpec extends AkkaSpec("""
...
+      }
+    }
+
+    import system.dispatcher
+
+    val transport = new CustomTransport
+    val poolSettings =
+      ConnectionPoolSettings(system)
+        .withTransport(transport)
+        .withConnectionSettings(ClientConnectionSettings(system).withIdleTimeout(23.hours))
```
Comment (ktoso) [inline akka-http-core/src/test/scala/akka/http/impl/engine/client/ConnectionPoolSpec.scala]: extract the `23.hours` as value? a bit easier to see where it's set / expected then?

File: akka-http-core/src/test/scala/akka/http/impl/engine/client/ConnectionPoolSpec.scala [hunk 6]
```diff
@@ -566,4 +591,45 @@ class ConnectionPoolSpec extends AkkaSpec("""
...
+    transport.in.expectUtf8EncodedString("GET /test HTTP/1.1\r\n")
+    transport.out.sendNext(ByteString("HTTP/1.1 200 OK\r\nConnection: close\r\n\r\n"))
+
+    val response = responseFuture.awaitResult(10.seconds)
+    response.status should ===(StatusCodes.OK)
+    transport.out.sendNext(ByteString("Hello World!"))
+    transport.out.sendComplete()
+
+    response.entity.dataBytes.utf8String.awaitResult(10.seconds) should ===("Hello World!")
+  }
```
Comment (ktoso) [inline akka-http-core/src/test/scala/akka/http/impl/engine/client/ConnectionPoolSpec.scala]: Great test setup!

**Comment by ktoso** [comment]
> There is a basic disadvantage of passing ClientConnectionSettings to the connectTo method which is that whatever settings future ClientTransport come up with, they have to be put into those ClientConnectionSettings, so this might become an even bigger grab bag than it is right now.

Yeah... though perhaps won't been much more of a problem than it is already in practice; For now we only have the Proxy coming up there AFAICS; Technically we could pull off some trick like transportSettings: Map[TransportSettingKey[V], V] or something if we care about avoiding more fields in there etc (would allow keeping external projects to contribute transports - though I'm not sure that will happen or should be a goal - what was your plan about that?)

File: akka-http-core/src/main/scala/akka/http/scaladsl/Http.scala (hunk 2 above)
Comment (jrudolph) [inline akka-http-core/src/main/scala/akka/http/scaladsl/Http.scala]: No, the problem was that `ConnectionPoolSettings.withConnectionSettings(...)` had no effect because the settings had already been passed to the transport.
