### PR TITLE
=htp #459 prevent "Connection closed by peer" errors during connection closure

### LINKED ISSUE #459: TCP RST was sent with large response body
Akka HTTP version: 3.0.0-RC1

How to reproduce:

 - Use small MTU for network interface (for example 1500). You can set MTU for loopback interface with `sudo ifconfig lo0 mtu 1500`
 - Response with large body content (should be larger than 128KiB) using `complete` and `ToResponseMarshallable`
 - Make sure client send header `Connection: close`.

Expected result:

Client should receive normally

Actual result:

Client got `Recv failure: Connection reset by peer`

This causes problems with some proxy like nginx or kong because they send `Connection: close` to upstream by default.

### PR DESCRIPTION
**Pull request by jrudolph**
A race between completion and cancellation towards the TCP stream endpoints
might lead to the connection being canceled (= RST frames sent) when an HTTP
connection is regularly closed (e.g. when the client sets `Connection: close`
in the request).

We now prevent cancellation from reaching the TCP stream at all and rely
on closing the connection from the write side.

Fixes #459.

### CODE REVIEW

File: akka-http-core/src/main/scala/akka/http/impl/util/StreamUtils.scala [hunk 1]
```diff
@@ -233,6 +233,24 @@ private[http] object StreamUtils {
...
   }
+
+  /**
+   * Returns a flow that is almost identity but doesn't pass cancellation from downstream to upstream.
+   *
+   * Note: This might create a resource leak if the upstream never completes. External measures
+   * need to be taken to ensure that the upstream will always complete.
+   */
+  def ignoreCancellation[T]: Flow[T, T, NotUsed] = Flow.fromGraph(new IgnoreCancellation)
+  class IgnoreCancellation[T] extends SimpleLinearGraphStage[T] {
```
Comment (viktorklang) [inline akka-http-core/src/main/scala/akka/http/impl/util/StreamUtils.scala]: @jrudolph  Apologies for the seemingly dumb question, but doesn't *ignoring cancellation* violate Reactive Streams?
(I'm more than likely missing something here?) Also public class and not final?

Comment (jrudolph) [inline akka-http-core/src/main/scala/akka/http/impl/util/StreamUtils.scala]: I guess the comment is not quite accurate. Cancellation is not ignored in the sense that the stage will sent additional elements after it received cancellation (that is already prevented by the GraphStage). It is just not propagated to the upstream side of this flow in this case. (The default behavior when receiving cancellation will call `completeStage` which is correct for most flow-like stages but for many others it isn't.)

Also, it's only a utility class. As explained (also in the other comment in Http.scala) it is only used in circumstances where the overall setup ensures that a flow (or complete graph setup) is closed from the other side.

And, yes, `final` would make sense, it already lives in a `private[http]` object.

Comment (ktoso) [inline akka-http-core/src/main/scala/akka/http/impl/util/StreamUtils.scala]: Yeah the GraphStage upholds all RS rules, so we won't be able to push a closed port - it'll throw "can not push closed port". We could avoid that risk, and make it explicit that this won't happen by doing

```
override def onDownstreamFinish(): Unit = {
  // don't pass cancellation to upstream, and
  setHandler(in, new OutHandler { def onPush(): Unit = log.debug("received unexpected push after cancellation swallowed") } 
}

```

Comment (ktoso) [inline akka-http-core/src/main/scala/akka/http/impl/util/StreamUtils.scala]: Also, perhaps changing name slightly would be good? Like `BarrierCancellation` / `BarrierCancellation`?
I've had instances where I needed to barrier off completion too, so that would make it naming wise simple to add such one too once needed again

Comment (viktorklang) [inline akka-http-core/src/main/scala/akka/http/impl/util/StreamUtils.scala]: @jrudolph @ktoso As you say, the comment/explanation/name is slightly misleading. It's really about something like "AbsorbCancellationStage"?

Comment (viktorklang) [inline akka-http-core/src/main/scala/akka/http/impl/util/StreamUtils.scala]: And, great fix btw!

Comment (ktoso) [inline akka-http-core/src/main/scala/akka/http/impl/util/StreamUtils.scala]: Might as well revive the old `absorb` wording for these, why not 👍

Comment (jrudolph) [inline akka-http-core/src/main/scala/akka/http/impl/util/StreamUtils.scala]: Thanks, @ktoso and @viktorklang. Good comments. Fixed!

File: akka-http-core/src/main/scala/akka/http/impl/util/StreamUtils.scala [hunk 2]
```diff
@@ -233,6 +233,29 @@ private[http] object StreamUtils {
...
+  final class AbsorbCancellationStage[T] extends SimpleLinearGraphStage[T] {
+    def createLogic(inheritedAttributes: Attributes): GraphStageLogic = new GraphStageLogic(shape) with InHandler with OutHandler with StageLogging {
+      setHandlers(in, out, this)
+
+      def onPush(): Unit = push(out, grab(in)) // using `passAlong` was considered but it seems to need some boilerplate to make it work
+      def onPull(): Unit = pull(in)
+
+      override def onDownstreamFinish(): Unit = {
+        // don't pass cancellation to upstream, and ignore eventually outstanding future element
+        setHandler(in, new InHandler { def onPush(): Unit = log.debug("Ignoring unexpected data received after cancellation was ignored.") })
```
Comment (ktoso) [inline akka-http-core/src/main/scala/akka/http/impl/util/StreamUtils.scala]: yup cool

**Comment by ktoso** [comment]
LGTM, great - and great new names :)
