### PR TITLE
Fix cancellation race conditions on the client-side

### LINKED ISSUE #2349: GracefulTerminationSpec: Expected exception akka.stream.StreamTcpException to be thrown, but akka.http.impl.engine.client.pool.SlotState$BusyState$$anon$1 was thrown
https://jenkins.akka.io:8498/job/pr-validator-akka-http/3092/testReport/junit/akka.http.scaladsl/GracefulTerminationSpec/Graceful_termination_should_in_flight_request_responses_should_include_Connection__close_and_connection_should_be_closed/
```
org.scalatest.exceptions.TestFailedException: Expected exception akka.stream.StreamTcpException to be thrown, but akka.http.impl.engine.client.pool.SlotState$BusyState$$anon$1 was thrown
	at org.scalatest.MatchersHelper$.newTestFailedException(MatchersHelper.scala:138)
	at org.scalatest.MatchersHelper$.checkExpectedException(MatchersHelper.scala:312)
	at org.scalatest.words.ResultOfTheTypeInvocation.thrownBy(ResultOfTheTypeInvocation.scala:39)
	at akka.http.scaladsl.GracefulTerminationSpec.akka$http$scaladsl$GracefulTerminationSpec$$ensureConnectionIsClosed(GracefulTerminationSpec.scala:193)
	at akka.http.scaladsl.GracefulTerminationSpec$$anon$6.<init>(GracefulTerminationSpec.scala:137)
	at akka.http.scaladsl.GracefulTerminationSpec.$anonfun$new$10(GracefulTerminationSpec.scala:123)
```

### PR DESCRIPTION
**Pull request by jrudolph**
Divide and conquer of the (too) big change in #2678.

Finally fixes #2349, the longest-standing recurrent failure.

### CODE REVIEW

File: akka-http-core/src/main/scala/akka/http/scaladsl/Http.scala [hunk 1]
```diff
@@ -1127,6 +1136,14 @@ object Http extends ExtensionId[HttpExt] with ExtensionIdProvider {
...
     else HttpAttributes.empty
 
+  @InternalApi
+  private[http] def cancellationStrategyAttributeForDelay(delay: FiniteDuration): Attributes =
+    Attributes(CancellationStrategy {
+      delay match {
+        case Duration.Zero => FailStage
+        case d             => AfterDelay(d, FailStage)
+      }
+    })
```
Comment (raboof) [inline akka-http-core/src/main/scala/akka/http/scaladsl/Http.scala]: :+1:
