### PR TITLE
Fix build against akka master

### LINKED ISSUE #3633: Failure: Http2ServerSpec.The Http/2 server implementation should support stream for request entity data should not leak stream if request entity is not fully pulled when connection dies
https://jenkins.akka.io:8498/job/akka-http-nightly/AKKA_VERSION=master,Node=akka-http-nightly-node,SCALA_VERSION=2.12.12,jdk=AdoptOpenJDK%2011/331/testReport/junit/akka.http.impl.engine.http2/Http2ServerSpec/The_Http_2_server_implementation_should_support_stream_for_request_entity_data_should_not_leak_stream_if_request_entity_is_not_fully_pulled_when_connection_dies/

Looks like a stream leak
```
assertion failed: expected no StreamSupervisor children, but got [Actor[akka://Http2ServerSpec/system/Materializers/StreamSupervisor-10/flow-35-0-filter#1578801161]]
	at scala.Predef$.assert(Predef.scala:223)
	at akka.stream.testkit.scaladsl.StreamTestKit$.$anonfun$assertNoChildren$2(StreamTestKit.scala:54)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at akka.testkit.TestKitBase.poll$2(TestKit.scala:330)
	at akka.testkit.TestKitBase.awaitAssert(TestKit.scala:347)
	at akka.testkit.TestKitBase.awaitAssert$(TestKit.scala:319)
	at akka.testkit.TestKit.awaitAssert(TestKit.scala:969)
	at akka.stream.testkit.scaladsl.StreamTestKit$.$anonfun$assertNoChildren$1(StreamTestKit.scala:51)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at akka.testkit.TestKitBase.within(TestKit.scala:416)
	at akka.testkit.TestKitBase.within$(TestKit.scala:404)
	at akka.testkit.TestKit.within(TestKit.scala:969)
	at akka.testkit.TestKitBase.within(TestKit.scala:431)
	at akka.testkit.TestKitBase.within$(TestKit.scala:431)
	at akka.testkit.TestKit.within(TestKit.scala:969)
	at akka.stream.testkit.scaladsl.StreamTestKit$.assertNoChildren(StreamTestKit.scala:51)
	at akka.stream.testkit.scaladsl.StreamTestKit$.assertAllStagesStopped(StreamTestKit.scala:33)
	at akka.http.impl.engine.http2.Http2ServerSpec$InWithStoppedStages.$anonfun$inAssertAllStagesStopped$1(Http2ServerSpec.scala:1273)
```

### PR DESCRIPTION
**Pull request by jrudolph**
Fixes #3633, #3634

### CODE REVIEW

File: akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ServerSpec.scala [hunk 1]
```diff
@@ -432,29 +432,38 @@ class Http2ServerSpec extends AkkaSpecWithMaterializer("""
...
         expectRST_STREAM(TheStreamId, ErrorCode.FLOW_CONTROL_ERROR)
       }
-      "not leak stream if request entity is not fully pulled when connection dies" inAssertAllStagesStopped new WaitingForRequestData {
+      "fail stream if request entity is not fully pulled when connection dies" inAssertAllStagesStopped new WaitingForRequestData {
         sendDATA(TheStreamId, endStream = false, ByteString("0000"))
         entityDataIn.expectUtf8EncodedString("0000")
         pollForWindowUpdates(500.millis)
 
-        sendDATA(TheStreamId, endStream = false, ByteString("1111"))
+        val bigData = ByteString("1" * 100000) // more than configured request-entity-chunk-size, so that something is left in buffer
```
Comment (jrudolph) [inline akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ServerSpec.scala:440]: This is necessary to avoid the difference between Akka 2.5 and 2.6 which seems to be in buffering (maybe related to `Flow.filter` changes in 2.6).

Comment (raboof) [reply akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ServerSpec.scala:440]: if it's `big data` it must be good :D

**Review by raboof — APPROVED** [review]
:+1:

File: akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ServerSpec.scala (hunk 1 above)
Comment (jrudolph) [reply akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ServerSpec.scala:440]: Indeed!

```suggestion
        val BIGDATAAAAAA = ByteString("1" * 100000) // more than configured request-entity-chunk-size, so that something is left in buffer
```

**Review by johanandren — APPROVED** [review]
